# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.setEnabled(True)
        Interface.resize(738, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Interface.sizePolicy().hasHeightForWidth())
        Interface.setSizePolicy(sizePolicy)
        Interface.setMinimumSize(QtCore.QSize(0, 0))
        Interface.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Interface.setWindowOpacity(1.0)
        Interface.setAutoFillBackground(False)
        Interface.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Interface)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_radar = QtWidgets.QVBoxLayout()
        self.verticalLayout_radar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_radar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_radar.setObjectName("verticalLayout_radar")
        self.gridLayout.addLayout(self.verticalLayout_radar, 0, 1, 5, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.aerodromes = QtWidgets.QHBoxLayout()
        self.aerodromes.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.aerodromes.setContentsMargins(-1, 0, -1, -1)
        self.aerodromes.setObjectName("aerodromes")
        self.label_10 = QtWidgets.QLabel(Interface)
        self.label_10.setObjectName("label_10")
        self.aerodromes.addWidget(self.label_10)
        self.pushButton_a = QtWidgets.QPushButton(Interface)
        self.pushButton_a.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a.sizePolicy().hasHeightForWidth())
        self.pushButton_a.setSizePolicy(sizePolicy)
        self.pushButton_a.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_a.setObjectName("pushButton_a")
        self.aerodromes.addWidget(self.pushButton_a)
        self.verticalLayout.addLayout(self.aerodromes)
        self.Vents = QtWidgets.QHBoxLayout()
        self.Vents.setContentsMargins(-1, 0, -1, 10)
        self.Vents.setObjectName("Vents")
        self.label_11 = QtWidgets.QLabel(Interface)
        self.label_11.setObjectName("label_11")
        self.Vents.addWidget(self.label_11)
        self.pushButton_v = QtWidgets.QPushButton(Interface)
        self.pushButton_v.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_v.sizePolicy().hasHeightForWidth())
        self.pushButton_v.setSizePolicy(sizePolicy)
        self.pushButton_v.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_v.setObjectName("pushButton_v")
        self.Vents.addWidget(self.pushButton_v)
        self.verticalLayout.addLayout(self.Vents)
        self.dep = QtWidgets.QHBoxLayout()
        self.dep.setContentsMargins(-1, -1, 0, -1)
        self.dep.setObjectName("dep")
        self.label_12 = QtWidgets.QLabel(Interface)
        self.label_12.setStyleSheet("")
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.dep.addWidget(self.label_12)
        self.comboBox_depart = QtWidgets.QComboBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_depart.sizePolicy().hasHeightForWidth())
        self.comboBox_depart.setSizePolicy(sizePolicy)
        self.comboBox_depart.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_depart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_depart.setEditable(True)
        self.comboBox_depart.setObjectName("comboBox_depart")
        self.dep.addWidget(self.comboBox_depart)
        self.verticalLayout.addLayout(self.dep)
        self.arr = QtWidgets.QHBoxLayout()
        self.arr.setObjectName("arr")
        self.label_13 = QtWidgets.QLabel(Interface)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.arr.addWidget(self.label_13)
        self.comboBox_arrive = QtWidgets.QComboBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_arrive.sizePolicy().hasHeightForWidth())
        self.comboBox_arrive.setSizePolicy(sizePolicy)
        self.comboBox_arrive.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_arrive.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_arrive.setEditable(True)
        self.comboBox_arrive.setObjectName("comboBox_arrive")
        self.arr.addWidget(self.comboBox_arrive)
        self.verticalLayout.addLayout(self.arr)
        self.heure_du_vol = QtWidgets.QHBoxLayout()
        self.heure_du_vol.setObjectName("heure_du_vol")
        self.label_14 = QtWidgets.QLabel(Interface)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.heure_du_vol.addWidget(self.label_14)
        self.timeEdit = QtWidgets.QTimeEdit(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setMinimumSize(QtCore.QSize(120, 0))
        self.timeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timeEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.timeEdit.setObjectName("timeEdit")
        self.heure_du_vol.addWidget(self.timeEdit)
        self.verticalLayout.addLayout(self.heure_du_vol)
        self.vitesse = QtWidgets.QHBoxLayout()
        self.vitesse.setContentsMargins(-1, -1, -1, 0)
        self.vitesse.setObjectName("vitesse")
        self.label_15 = QtWidgets.QLabel(Interface)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.vitesse.addWidget(self.label_15)
        self.spinBox_vitesse = QtWidgets.QSpinBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_vitesse.sizePolicy().hasHeightForWidth())
        self.spinBox_vitesse.setSizePolicy(sizePolicy)
        self.spinBox_vitesse.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_vitesse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBox_vitesse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_vitesse.setMaximum(400)
        self.spinBox_vitesse.setProperty("value", 200)
        self.spinBox_vitesse.setObjectName("spinBox_vitesse")
        self.vitesse.addWidget(self.spinBox_vitesse)
        self.verticalLayout.addLayout(self.vitesse)
        self.altitude_min = QtWidgets.QHBoxLayout()
        self.altitude_min.setContentsMargins(-1, -1, -1, 0)
        self.altitude_min.setObjectName("altitude_min")
        self.label_16 = QtWidgets.QLabel(Interface)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.altitude_min.addWidget(self.label_16)
        self.spinBox_pression_inf = QtWidgets.QSpinBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pression_inf.sizePolicy().hasHeightForWidth())
        self.spinBox_pression_inf.setSizePolicy(sizePolicy)
        self.spinBox_pression_inf.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_pression_inf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBox_pression_inf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_pression_inf.setMinimum(400)
        self.spinBox_pression_inf.setMaximum(800)
        self.spinBox_pression_inf.setSingleStep(100)
        self.spinBox_pression_inf.setObjectName("spinBox_pression_inf")
        self.altitude_min.addWidget(self.spinBox_pression_inf)
        self.verticalLayout.addLayout(self.altitude_min)
        self.altitude_max = QtWidgets.QHBoxLayout()
        self.altitude_max.setContentsMargins(-1, -1, -1, 0)
        self.altitude_max.setObjectName("altitude_max")
        self.label_17 = QtWidgets.QLabel(Interface)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.altitude_max.addWidget(self.label_17)
        self.spinBox_pression_sup = QtWidgets.QSpinBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pression_sup.sizePolicy().hasHeightForWidth())
        self.spinBox_pression_sup.setSizePolicy(sizePolicy)
        self.spinBox_pression_sup.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_pression_sup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBox_pression_sup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_pression_sup.setMinimum(400)
        self.spinBox_pression_sup.setMaximum(800)
        self.spinBox_pression_sup.setSingleStep(100)
        self.spinBox_pression_sup.setProperty("value", 800)
        self.spinBox_pression_sup.setObjectName("spinBox_pression_sup")
        self.altitude_max.addWidget(self.spinBox_pression_sup)
        self.verticalLayout.addLayout(self.altitude_max)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(Interface)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.spinBox_tempsdarret = QtWidgets.QSpinBox(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_tempsdarret.sizePolicy().hasHeightForWidth())
        self.spinBox_tempsdarret.setSizePolicy(sizePolicy)
        self.spinBox_tempsdarret.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_tempsdarret.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinBox_tempsdarret.setStyleSheet("")
        self.spinBox_tempsdarret.setMaximum(600)
        self.spinBox_tempsdarret.setProperty("value", 20)
        self.spinBox_tempsdarret.setObjectName("spinBox_tempsdarret")
        self.horizontalLayout_4.addWidget(self.spinBox_tempsdarret)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.recherche = QtWidgets.QHBoxLayout()
        self.recherche.setContentsMargins(-1, 10, -1, 0)
        self.recherche.setObjectName("recherche")
        self.pushButton_calculer = QtWidgets.QPushButton(Interface)
        self.pushButton_calculer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_calculer.sizePolicy().hasHeightForWidth())
        self.pushButton_calculer.setSizePolicy(sizePolicy)
        self.pushButton_calculer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_calculer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_calculer.setAutoFillBackground(False)
        self.pushButton_calculer.setStyleSheet("")
        self.pushButton_calculer.setAutoDefault(False)
        self.pushButton_calculer.setDefault(False)
        self.pushButton_calculer.setFlat(False)
        self.pushButton_calculer.setObjectName("pushButton_calculer")
        self.recherche.addWidget(self.pushButton_calculer, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.recherche)
        self.verticalLayout_save = QtWidgets.QVBoxLayout()
        self.verticalLayout_save.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_save.setObjectName("verticalLayout_save")
        self.pushButton_save = QtWidgets.QPushButton(Interface)
        self.pushButton_save.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_save.addWidget(self.pushButton_save, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.verticalLayout_save)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Interface)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalSlider = QtWidgets.QSlider(Interface)
        self.verticalSlider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider.sizePolicy().hasHeightForWidth())
        self.verticalSlider.setSizePolicy(sizePolicy)
        self.verticalSlider.setMinimumSize(QtCore.QSize(0, 200))
        self.verticalSlider.setMinimum(400)
        self.verticalSlider.setMaximum(800)
        self.verticalSlider.setSingleStep(100)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayout_2.addWidget(self.verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.lcdNumber_pression = QtWidgets.QLCDNumber(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_pression.sizePolicy().hasHeightForWidth())
        self.lcdNumber_pression.setSizePolicy(sizePolicy)
        self.lcdNumber_pression.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_pression.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_pression.setFont(font)
        self.lcdNumber_pression.setStyleSheet("")
        self.lcdNumber_pression.setDigitCount(3)
        self.lcdNumber_pression.setObjectName("lcdNumber_pression")
        self.verticalLayout_2.addWidget(self.lcdNumber_pression, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listWidget.setStyleSheet("")
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 3, 1)
        self.frame = QtWidgets.QFrame(Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 2, 2, 2, 1)

        self.retranslateUi(Interface)
        self.verticalSlider.valueChanged['int'].connect(self.lcdNumber_pression.display)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "IHM de recherche de trajectoire optimale"))
        self.label_10.setText(_translate("Interface", "Fichier des aérodromes"))
        self.pushButton_a.setText(_translate("Interface", "Parcourir..."))
        self.label_11.setText(_translate("Interface", "Fichiers des vents"))
        self.pushButton_v.setText(_translate("Interface", "Parcourir..."))
        self.label_12.setText(_translate("Interface", "Aerodrome de départ"))
        self.label_13.setText(_translate("Interface", "Aerodrome d\'arrivé"))
        self.label_14.setText(_translate("Interface", "Heure du vol (hh:mm:ss)"))
        self.timeEdit.setDisplayFormat(_translate("Interface", "HH:mm:ss"))
        self.label_15.setText(_translate("Interface", "Vitesse de croisière"))
        self.label_16.setText(_translate("Interface", "Pression minimale (hPa)"))
        self.label_17.setText(_translate("Interface", "Pression maximale (hPa)"))
        self.label_18.setText(_translate("Interface", "Temps d\'arrêt (min)"))
        self.pushButton_calculer.setText(_translate("Interface", "Calculer"))
        self.pushButton_save.setText(_translate("Interface", "save"))
        self.label_3.setText(_translate("Interface", "hPa"))

