# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import math

class PanZoomView(QtWidgets.QGraphicsView):
    """An interactive view that supports Pan and Zoom functions"""

    def __init__(self, scene):
        super().__init__(scene)
        # enable anti-aliasing
        self.setRenderHint(QtGui.QPainter.Antialiasing)
        # enable drag and drop of the view
        self.setDragMode(self.ScrollHandDrag)

    def wheelEvent(self, event):
        """Overrides method in QGraphicsView in order to zoom it when mouse scroll occurs"""
        factor = math.pow(1.001, event.angleDelta().y())
        self.zoom_view(factor)

    @QtCore.pyqtSlot(int)
    def zoom_view(self, factor):
        """Updates the zoom factor of the view"""
        self.setTransformationAnchor(self.AnchorUnderMouse)
        super().scale(factor, factor)


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(867, 613)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Interface)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 866, 602))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hor_global = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hor_global.setContentsMargins(0, 0, 0, 0)
        self.hor_global.setObjectName("hor_global")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dep = QtWidgets.QHBoxLayout()
        self.dep.setContentsMargins(-1, -1, 0, -1)
        self.dep.setObjectName("dep")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.dep.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.dep.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.dep)
        self.arr = QtWidgets.QHBoxLayout()
        self.arr.setObjectName("arr")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.arr.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.arr.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.arr)
        self.heure_du_vol = QtWidgets.QHBoxLayout()
        self.heure_du_vol.setObjectName("heure_du_vol")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.heure_du_vol.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.heure_du_vol.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.heure_du_vol)
        self.vitesse = QtWidgets.QHBoxLayout()
        self.vitesse.setContentsMargins(-1, -1, -1, 0)
        self.vitesse.setObjectName("vitesse")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.vitesse.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spinBox.setMaximum(400)
        self.spinBox.setProperty("value", 200)
        self.spinBox.setObjectName("spinBox")
        self.vitesse.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.vitesse)
        self.altitude_min = QtWidgets.QHBoxLayout()
        self.altitude_min.setContentsMargins(-1, -1, -1, 0)
        self.altitude_min.setObjectName("altitude_min")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.altitude_min.addWidget(self.label_5)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spinBox_2.setMinimum(400)
        self.spinBox_2.setMaximum(800)
        self.spinBox_2.setSingleStep(100)
        self.spinBox_2.setObjectName("spinBox_2")
        self.altitude_min.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.altitude_min)
        self.altitude_max = QtWidgets.QHBoxLayout()
        self.altitude_max.setContentsMargins(-1, -1, -1, 0)
        self.altitude_max.setObjectName("altitude_max")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.altitude_max.addWidget(self.label_6)
        self.spinBox_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spinBox_3.setMinimum(400)
        self.spinBox_3.setMaximum(800)
        self.spinBox_3.setSingleStep(100)
        self.spinBox_3.setProperty("value", 800)
        self.spinBox_3.setObjectName("spinBox_3")
        self.altitude_max.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.altitude_max)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.spinBox_4 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_4.setMinimumSize(QtCore.QSize(120, 0))
        self.spinBox_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spinBox_4.setMaximum(600)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_3.addWidget(self.spinBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.recherche = QtWidgets.QHBoxLayout()
        self.recherche.setContentsMargins(-1, 50, -1, 0)
        self.recherche.setObjectName("recherche")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.recherche.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.recherche)
        self.text_browser = QtWidgets.QHBoxLayout()
        self.text_browser.setObjectName("text_browser")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.text_browser.addWidget(self.listWidget)
        self.verticalLayout.addLayout(self.text_browser)
        self.hor_global.addLayout(self.verticalLayout)
        self.scene = QtWidgets.QGraphicsScene()
        self.graphicsView = PanZoomView(self.scene)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setMinimumSize(QtCore.QSize(600, 600))
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.graphicsView.setObjectName("graphicsView")
        self.hor_global.addWidget(self.graphicsView, 0, QtCore.Qt.AlignLeft)
        self.graphicsView.raise_()

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "Form"))
        self.label.setText(_translate("Interface", "Aerodrome de départ"))
        self.lineEdit.setText(_translate("Interface", "LFBO"))
        self.label_2.setText(_translate("Interface", "Aerodrome d\'arrivé"))
        self.lineEdit_2.setText(_translate("Interface", "LFQQ"))
        self.label_3.setText(_translate("Interface", "Heure du vol (hh:mm:ss)"))
        self.lineEdit_3.setText(_translate("Interface", "13:30:00"))
        self.label_4.setText(_translate("Interface", "Vitesse de croisière"))
        self.label_5.setText(_translate("Interface", "Altitude minimale (hPa)"))
        self.label_6.setText(_translate("Interface", "Altitude maximale (hPa)"))
        self.label_7.setText(_translate("Interface", "Temps d\'arrêt (min)"))
        self.pushButton.setText(_translate("Interface", "Recherche"))

